### ISSUE TITLE
Error during mvn build "variable 'env.BUILD_NAME' has no value" in master tag 68d475a  

### ISSUE THREAD

**Issue by akubot-admin** [carnellj/spmia-chapter10#2]
I did a git clone of chapter 10, then

*mvn clean package docker:build*

The build fails, and at the end the error is

   *variable 'env.BUILD_NAME' has no value*

I'm using

Apache Maven 3.5.4
java version "1.8.0_152"
git version 2.20.1
Docker version 18.09.1, build 4c52b90
Mac OS X  10.12.6

Chapters 1-9 built just fine

I made a minor change to the pom.xml file, to change the Spring Boot version to 1.4.4.RELEASE as in Chapter 9 pom, but the build error is the same.

BTW the README here for Chapter 10 may have a typo, references Ch 9.

**Comment by jacek-s** [comment]
`BUILD_NAME` environment variable is exported by travis - see .travis.yml.

I'm assuming you don't build with travis but do a manual maven build, hence it's not going to be set.

**Comment by akubot-admin** [comment]
Hi, you are correct:  I was not using Travis. I see what you mean about the file `.travis.yml` which contains 

`export BUILD_NAME . . .`

thanks,

Harry
